# REMOVE THIS

# DO NOT REMOVE THIS
theme = "hugo-theme-codex"

# Override these settings with your own
title = "Home"
languageCode = "en-us"
baseURL = "https://tudorschlanger.com/"
copyright = "© 2021. All rights reserved. The views expressed on this website are solely my own. No responsibility for them should be attributed to the Bank of Canada."

# Add your Disqus shortname here.
disqusShortname = "tudorschlanger-com" # delete this to disable disqus comments

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-163330696-1"

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2 Jan 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/tudorschlanger"
  github = "https://github.com/tudorschlanger"
  email = "mailto:tudor.schlanger@gmail.com"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  linkedin = "https://www.linkedin.com/in/tudor-schlanger/"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["LinkedIn", "GitHub", "Email"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"



