---
author: "Tudor Schlanger"

# The title of your post. Default value is generated
# From the markdown filename
title: "COVID-19, Climate Change and the Tragedy of Horizons"
# The date the post was created
date: 2020-04-20
# The post filename
slug: "tragedy-of-horizons"
# Post description used for seo
description: ""
# Post keywords used for seo
keywords: ["COVID-19", "climate change"]
# If true, the blog post will not be included in static build
draft: false
# Categorize your post with tags
tags: ["COVID-19", "climate change"]
# Uses math typesetting
math: true
# Includes a table of contents on screens >1024px
toc: false

---


### In the previous episode ... 

In my previous **[post](/blog/econ-of-epidemics/)**, I was arguing that the current containment measures are not only a safeguard of human lives but also of longer term economic prosperity. They prevent us from making short-sighted gains at the price of our safety and the economy's future productive capacity. In a nutshell, containment measures allow us to internalize the virus externality that arises from our economic activity and improve social welfare overall.

In this post, I want to dig deeper into the concept of externality, and provide a simple explanation for why we choose to mitigate or fully internalize an externality in some cases but not in others. To flesh this point out, I will contrast the current COVID-19 crisis to a larger one that is looming in the horizon: climate change. 

### Thinking of COVID-19 as an externality

This idea of an externality was first articulated by Henry Sidgwick and then by Arthur Pigou in his work, the **[Economics of Welfare](http://pombo.free.fr/pigou1920.pdf)**, which was published exactly 100 years ago! To pay homage to the latter and celebrate his work, I will quote his formulation of the idea:

> Here the essence of the matter is that one person A, in the course of rendering some service,
for which payment is made, to a second person B, incidentally also renders services or disservices to other persons C, D and E, of such a sort that technical considerations prevent payment being exacted from the benefited parties or compensation being enforced on behalf of the injured parties. 

In 2020 plain language, this means an externality is a by-product of an economic transaction (between A and B) that affects people who are not involved in the transaction (i.e. C, D, and E). The externality can be positive of negative depending on whether it positvely or negatively affects other people. 

The current COVID-19 virus can be considered a *negative* externality. For instance, an infected customer who goes to a restaurant and pays for a meal does not incur the cost the restaurant staff incurs when they are infected with the virus and need to stay home. The customer does not pay for the full cost that the health system incurs with the additional newly infected and hospitalized people. Taking this one tragic step further, the customer does not incur the cost of higher mortality that he contributed to as a result of his transaction.  

If we were to tally up with certainty the costs society incurs from this one simple restaurant transaction and add it to the customer's bill, we could say that we internalized the externality. Having imposed this tax, society can cover for all those costs. However, the tax would be so high that the benefits of eating one meal are far outweighed by the immense cost of the tax, and so, the customer would rather not make the transaction. Hence, society would benefit from lesser demand of transactions which propagate the virus. This is the beauty of the Pigouvian tax! 

Evidently, for practical reasons we would never be able to fully estimate the social cost of the transaction. For instance, it is hard to estimate the statistical value of a human life. And even if we had that information, a government authority would never be able to impose a tax that would cover for the cost. It is much more feasible and effective to prohibit such transactions from taking place - hence the use of containment measures!

### A Tale of Two Externalities

The COVID-19 virus is not the only sizeable externality out there; there is a larger one, yet far less conspicuous, which looming in the background and in the future. In the **[Stern Review](http://mudancasclimaticas.cptec.inpe.br/~rmclima/pdfs/destaques/sternreview_report_complete.pdf)**, one of the first major publications to document and forecast the effects of climate change, the authors argue that "climate change is the greatest market failure the world has ever seen." Here, market failure is equivalent to a negative externality. It reflects the markets' inability to internalize the cost of greenhouse gas emissions which is the externality that arises from the consumption and production of carbon-intensive goods and services. 

In many ways, this externality is similar to the virus one: both occur as an outcome of our economic activity and the expansion of the human habitats into nature; both inflict human and economic losses; both disproportionately affect poorer people especially in developing countries without the adequate infrastrcuture to bear the shocks; and both have a "Pandora box" effect by which the effects of the externality are somewhat irreversible and may be completely remedied only by the discovery of a "treatment." In the case of COVID-19, it is a vaccine or an actual treatment, and in the case of climate change it would be technologies that abruptly stop and revert the emissions of greenhouse gases into the atmosphere.

However, we have no such treatment for either externality, and we have to focus on the traditional ways to internalize them. As mentioned before, containment measures is the way in case of the virus. For climate change, the most common idea is the introduction of a tax on carbon emissions. 

The tax is supposed to be equal to the social cost of emitting a unit of carbon now and which will be born by future generations. This means that today's generation has to sacrifice income -- either by reduced output or through higher prices for their consumption of carbon-intensive goods and services -- in order to mitigate the damages that they or others will incur in the future.

But if this is a trade-off we are willing to make for COVID-19, why is it we are not willing to make it for climate change?

### A Tragedy of the Horizons 

We, as a society, are more comfortable to make a trade-off when we understand that:

- the costs of the negative externality are large and **certain** 
- these costs are incurred now or in the **very near future**
- **we** are likely to bear this cost

These are features that are not necessarily present in the climate change trade-off. The costs may be large but the magnitude is very uncertain. They are likely not going to affect the current generations as much as future ones. And they are far into the future, decades or even centuries. 

But even if we were able to pin point, to the second decimal, the dollar cost of an extra unit of carbon emissions and even if we were to live 200 years to bear the full costs of those emissions, it is unlikely that we would be eager to accept such a forward-looking trade-off.  

The main difference between the two externalities is the length of the horizon we consider to be relevant. The former Bank of England governor, Mark Carney, minted the term **["Tragedy of the Horizons."](https://www.bis.org/review/r151009a.pdf)** to describe that the catastrophic impacts of climate change will be felt beyond the traditional horizons of most actors. Just to take the horizons of some institutions: 

- **monetary policy:** Central banks look 2 to 3 years into the future
- **fiscal policy:** Politicians' mandates extend from 4 to 8 years
- **financial stability:** Fiscal stability authorities think 10 years ahead (based on the credit cycle)

Financial markets are arguably more short-sighted in many instances. And then there are individual people who have their own horizons. Maybe 5 years, maybe 50 years. Yet, is it even relevant to talk in terms of fixed values as if after a certain number of years nothing else mattered? In a future post, I will talk about *discount rates* as a more appropriate way to gauge society's implicit importance it gives to the future. 

### Last words...

For now, I am content to end this post by saying that the way we collectively accepted to sacrifice some economic wellbeing in the short-term to safeguard our wellbeing in the next months, for COVID-19, should make us think about accepting a similar trade-off that we are making in the long-term over the next year and decades, for climate change. This trade-off is captured by our choices to support a carbon tax and other measures to advance emission targets.

Even if it's described as a "tragedy of the horizons", it need not be perceived as the unavoidable course of fate. 




