---
author: "Tudor Schlanger"

# The title of your post. Default value is generated
# From the markdown filename
title: "Efficiency and Optimality"
# The date the post was created
date: "2020-09-01"
# The post filename
slug: "efficiency-and-optimality"
# Post description used for seo
description: ""
# Post keywords used for seo
keywords: ["ECON 101"]
# If true, the blog post will not be included in static build
draft: false
# Categorize your post with tags
tags: ["ECON 101"]
# Uses math typesetting
math: true
# Includes a table of contents on screens >1024px
toc: false
---

*This entry is the **first** of a two-part lecture written for the Econ 101 2020W class at the University of British Columbia, co-authored with Christina (Kit) Schwartz and Mauricio Drelichman.* 

In this reading we will explore how economists think about optimal or efficient allocations. “Optimal” and “efficient” are both nice-sounding words. In economics, however, these words have very specific meanings. Below we will define what they mean and, especially, what they do not mean.

### Pareto optimality
The most widely used concept of optimality in economics was put forward by Italian economist Vilfredo Pareto, to whom we also owe the Pareto statistical distribution and the Pareto principle (also known as the “80-20” principle). We say that an allocation of resources is Pareto-optimal if it is not possible to make a person better off without making someone else worse off.

To illustrate the concept, suppose that Erin and Josh both like fruit in general. However, Erin likes apples better than pears, while Josh likes pears better than apples. There is one pear and one apple in the economy.

First, we can establish that, in order for an allocation to be Pareto optimal, both fruits need to be given to someone. For example, giving the apple to Erin and throwing the pear away cannot be Pareto optimal – we could make either Josh or Erin better off by giving them the pear instead. This observation can be generalized by stating that every Pareto optimal allocation needs to fully utilize all available resources. No allocation that wastes resources can be Pareto optimal.

Let’s then consider all allocations that fully utilize the available resources – that is, the apple and the pear. There are four possibilities:

<ol type="a">
  <li> Erin gets both fruits </li>
  <li> Josh gets both fruits </li>
  <li> Erin gets the apple and Josh gets the pear </li>
  <li> Erin gets the pear and Josh gets the apple </li>
</ol>

Is allocation a) Pareto optimal? We could make Josh better off by taking the pear from Erin and giving it to him. However, this would make Erin worse off. Even though she likes apples better than pears, having both fruits is better than having just one of them. We cannot make Josh better off without making Erin worse off, and therefore allocation a) is Pareto optimal. By a similar reasoning, so is allocation b).
What about allocation c)? Here each person has their preferred fruit. The only way to make one of them better off is to give them both fruits, but this would make the other person worse off. Allocation c) is also Pareto optimal. 
In allocation d), both Erin and Josh have a fruit, but they both would prefer the other person’s fruit. We could get them to switch fruits, and this would make both of them better off. Allocation d) is not Pareto optimal. Switching Erin and Josh’s fruits is called a Pareto-improving trade.
 
The concept of Pareto optimality does not place any strong constraints on how resources should be distributed. In the above example, allocation c) has a relatively equal distribution of resources, with each person getting their preferred fruit. Allocations a) and b), on the other hand, are extremely unequal, with one person getting all the resources and the other person getting nothing. Yet all three allocations are Pareto optimal.

### Efficiency
In economic parlance, the term “efficiency” (or, more precisely, “allocative efficiency”) is used to describe a situation where every scarce resource is put to its highest-value use. Imagine an economy in which there is a single ticket to a movie theater, and a single restaurant meal. Tudor hates movies and enjoys gourmet meals. Kit loves movies and is happiest when eating pop-corn from the concession stand. Sending Tudor to the theatre and Kit to the restaurant would be a bad idea – allocative efficiency requires that Kit be given the movie ticket, and Tudor take the only available restaurant meal. The efficient allocation makes both Tudor and Kit happier than they would be under the alternative.

The above situation is an example of efficiency in consumption. An analog situation exists for the production side of the economy. Suppose the only two resources in the economy are a vineyard and an orchard. Tanya is great at growing grapes, and doesn’t know the first thing about apples. Joseph can tend to apple trees, but does not do well with vines. Clearly, allocative efficiency requires that Tanya be given the vineyard, and Joseph the orchard.

The above outcomes seem rather agreeable – everybody gets something they like, or are good at. This need not be the case, however. Suppose now that Tanya is better than Joseph at growing both apples and grapes, and that she has the time to manage both operations. In this case, allocative efficiency requires that we give both the orchard and the vineyard to Tanya, while Joseph gets nothing. This would maximize the productivity of the economy, even though it would clearly make Joseph very unhappy.

### Efficiency and Exchange: The Coase Theorem

Let’s return to Erin and Josh for a moment. Consider the non-optimal allocation d), in which each of them was given their least preferred fruit. If we put Erin and Josh face to face, each holding the fruit they are not so thrilled about, it wouldn’t take long for one of them to say “wanna trade?” A quick exchange later, each would be savoring their favourite fruit, and feeling quite snug about having restored Pareto optimality. What happened? We allowed Erin and Josh to transact.

An environment in which mutually agreeable transactions take place is what we call a market. Markets in which there are large numbers of buyers and sellers, and in which no individual agent is powerful enough to affect the market price on their own, are called “competitive”. In 1960, Nobel Laureate Ronald Coase showed that, if it is costless to transact, then the presence of a competitive market is enough to guarantee that an efficient allocation will emerge, regardless of the initial distribution of resources. 

That’s a lot to take in, so let’s take a step back and reflect on what the Coase Theorem tells us. First, an important caveat: “IF it is costless to transact”. That’s a big if. Transacting is usually costly. Before buying a product, we typically spend some time researching it, incurring information costs. In some cases, we have to bargain for the product, incurring negotiation costs. And sometimes we have to get the other party to hold up their end of the deal, perhaps by providing warranty service, and hence incur enforcement costs. These three types of costs – information, negotiation, and enforcement – are collectively known as “transaction costs”, and affect virtually every exchange. The first premise of the Coase Theorem is, therefore, not strictly true. 

There are, however, markets in which transaction costs are very small. Think about commodity markets. When you buy a future contract for a barrel of Texas Sweet Light Crude delivered in Houston, you know exactly what you get. All barrels of oil of a certain quality are the same. The exchange takes place on an electronic market, which charges a fraction of a cent for intermediating the transaction. And if you buy from a reputable provider of oil contracts, the enforcement costs will be zero. This is very close to Coase’s ideal, and many other markets also have sufficiently low transaction costs to warrant applying the theorem.

Back to the theorem: let’s now assume it is costless to transact. Then a competitive market will produce an efficient allocation REGARDLESS of the initial distribution of resources. Think about it for a minute. If we distribute all resources equally among all agents, the market will make sure that eventually we get an efficient allocation. But what if we give all the available resources to a single individual? No matter – the market will also ensure that an efficient allocation is reached. The resulting allocations may look different, but they will both be efficient, and Pareto optimal.
Since the Coase Theorem can be somewhat hard to grasp, let’s work through an example. Going back to Tanya and Joseph, let’s assume that their annual productivity in each plot of land is given by the following table:
<br><br>

<div align="center">
|        | Vineyard   |    Orchard  |  
|--------|------------|-------------|
| Tanya  | 100 grapes |  100 apples |  
| Joseph |  20 grapes |  20 apples  | 
</div>

The efficient allocation is clearly to give Tanya both the vineyard and the orchard, thus maximizing the economy’s output at a level of 100 grapes and 100 apples. Or is it? The Coase Theorem tells us that it really doesn’t matter where we start from. Let’s work through all possible scenarios.

In a first scenario, Tanya gets both the vineyard and the orchard. She produces 100 grapes and 100 apples. The economy is running at the efficient level. Nothing to see here.
Now let’s give the orchard to Joseph. If Tanya and Joseph each work their respective plots, output would be 100 grapes and 20 apples. This is not efficient, because Tanya could produce more apples if she was given the orchard. However, if it was costless to transact, Tanya would approach Joseph and say “nice orchard you’ve got there! Let me buy it from you. I will tend to it myself, and will pay you 21 apples at harvest time”. Because the price of 21 apples exceeds the 20 apples Joseph could produce tending to the orchard himself, he would accept. Tanya would work in the orchard and get 100 apples out of it. She would pay Joseph 21, and keep the remaining 79 for herself. The economy would once again run at the efficient level of 100 grapes and 100 apples. A similar mechanism would apply if  we gave Tanya the orchard and Joseph the vineyard.

What if the initial allocation is to give Joseph both plots? Tanya would just buy both from him, paying 21 grapes and 21 apples, and keeping 79 apples and 79 grapes from herself. In each of the four possible cases, regardless of the initial allocation of land, the market has ensured that each plot ends up in the hands of the most productive person, and that the economy runs at its full potential.

The Coase Theorem is very powerful. It tells us that, if efficiency is our ultimate goal, we need not worry about how resources are distributed. Instead, we just need to focus on reducing transaction costs as much as possible, make sure markets are competitive, and let them do their thing. Efforts to enhance the competitive environment via anti-trust laws and enforcement bodies, and institutional reforms to reduce the costs of doing business both find their theoretical foundations in the Coase Theorem.

### The trade-off between efficiency and equality

Efficiency is a key goal of economics. In almost every culture, children are taught that letting resources go to waste is a bad thing. A more efficient economy will produce higher levels of aggregate output; when we look at countries around the world, those with higher output rank higher in a wide variety of measures of living standards, including consumption, life expectancy, and a variety of freedoms. What’s not to like in efficiency?

Going back for a second to Tanya and Joseph, efficiency can be rather brutal. In the example in the table, Tanya is better than Joseph at growing both apples and grapes. All efficiency requires is that both resources in the economy – the vineyard and the orchard – be allocated to Tanya. Suppose that is indeed the initial allocation, as in the first scenario above. Even if there is a competitive market, Joseph would have nothing to offer on it, because he was allocated nothing to begin with. Tanya will have everything while Joseph starves to death. The situation is efficient – but is it fair?

If we decide that starvation is not an acceptable outcome, we have a few options. First, we could stage an agrarian revolution, taking part of the land from Tanya and giving it to Joseph. If there is no market for land, then Joseph would have to grow his own fruit. He now has enough to eat, and hence the allocation is more equal than before. However, he is not as good as Tanya growing fruit, and so the economy is less efficient. Directly allocating factors of production and prohibiting markets in them was an approach implemented by several 20th century communist regimes; they achieved higher equality, at the cost of sacrificing a lot of efficiency.

An alternative is to let Tanya work both the orchard and the vineyard. After the harvest, we take part of her output and give it to Joseph. This process is called redistributive taxation, and is used by every capitalist economy. While the resources remain in Tanya’s more productive hands, there is typically an efficiency cost nonetheless. Knowing that part of her output will be given to Joseph, Tanya may choose not to work as hard, and the economy will produce less. Part of the taxes also need to be spent on the structure of the tax system – calculating how much Tanya owes, sending the tax collectors to get the fruit, throwing her in jail if she doesn’t pay. That part of the output never reaches Joseph – it is lost. The final allocation is still more equal than before, because Joseph doesn’t starve to death, but less efficient.

What these crude examples illustrate is the idea that there is a trade-off between efficiency and equality. The more equal we wish an economy to be, the higher the reduction in its efficiency we have to accept. Taking things to one extreme: suppose we want a society in which everyone is guaranteed the same level of consumption. A person could reason that, since she is guaranteed her level of consumption no matter what, she may as well not work. Why bother? If everyone follows the same reasoning, however, the economy will produce no output. In practice, societies that pursue equality above all often resort to coercion in order to structure their economies. At the other extreme, things are more complicated. While in our example we had a perfectly efficient and perfectly unequal economy, there are constraints that prevent such scenarios. High levels of inequality tend to spur social unrest, which in turn starts threatening the efficiency of the economy. Most capitalist societies, therefore, adopt some level of redistribution before reaching the point where violence threatens economic efficiency.


