---
author: "Tudor Schlanger"

# The title of your post. Default value is generated
# From the markdown filename
title: "Basic Income: Not a Silver Bullet"
# The date the post was created
date: "2021-02-14"
# The post filename
slug: "basic-income"
# Post description used for seo
description: "A fresh perspective on Basic Income which views this policy from the lens of theories in political philosophy and psychology"
# Post keywords used for seo
keywords: ["Basic Income", "Political Philosophy"]
# If true, the blog post will not be included in static build
draft: false
# Categorize your post with tags
tags: ["Basic Income", "Political Philosophy"]
# Uses math typesetting
math: true
# Includes a table of contents on screens >1024px
toc: false
---

In this post, I would like to discuss a new and insightful perspective to this worldwide debate. Earlier this year, [a new report on Basic Income](https://bcbasicincomepanel.ca) - commissioned by the British Columbian government and authored by three economics professors in Western Canada - was released. The basic question they answer in this 500+ page report: Should we implement a Basic Income in this province? While the policy seems simple, feasible and as magical as a silver bullet, what one soon realises – just by looking at the page count - is that ... it’s not. 

TL;DR: The authors reach the conclusion that it is not worth having a basic income in BC.

Yet, this simple conclusion belies the complexity of the task at hand – and indeed, the conclusion is far less interesting than the journey they undertake to reach it. The authors offer a very nuanced, and comprehensive view of Basic Income – one that borrows from theories of justice and psychology to ascertain whether the Basic Income is a policy that is worth implementing. It is on this latter point that I will focus throughout this blog post. 


### Towards justice-based policy-making
The first step, and most important one in my view, that the authors undertake in their report is adopting a golden standard against which they can measure the success of the Basic Income policy. In other words, they say: what would be *the* thing that we want from an ideal policy, devised by a benevolent society for the benefit of all its members? The need for a golden standard is a much-needed exercise because of the magnitude of the undertaking. 

When it comes to a Basic Income policy, it is very important to understand that it is such a broad program that it affects society as a whole. It has far-reaching effects on the beneficiaries from this policy as well as its contributors; it has potentially important implications on the current social support system; and ultimately, it can fundamentally redesign the role of government, reshape our perception of the government and change our relation to other people in our society. If we are to redesign the current system, we may as well attempt to reach the ideal scenario, the best we can do.  

From the authors’ perspective, the success of a policy should be measured by its ability to lead to a more **just** society. [In a previous post](/blog/justice-and-fairness), I discuss some conceptions of justice, focusing on meritocracy, libertarianism and the Rawlsian theory of justice. The Report relies more on the intellectual legacy of the latter – but it also draws from other political philosophers, such as the founding father of economics, Adam Smith. 

In his (less-well-known-among-economists) [Theory of Moral Sentiments](https://www.adamsmith.org/the-theory-of-moral-sentiments), Smith claims that “The most effective societal institutions recognize and enhance our social nature as well as our individual nature.” (cited in the Report) These institutions, which can range from the executive to the legal institutions or even the rules/laws that distribute resources in our society, should strengthen the social fabric and build “mutual sympathy” between members of a society. In essence, a good policy would be a rule that empowers individuals but also brings people together, by making individuals concerned for each other’s circumstances and push them to act in accordance to that concern.  

The authors are quite aware that the social aspect may trump the individual considerations – they invoke Rawls here: “The central problem of justice is how to balance our social nature with individual rights.” Should society have so much consideration and “sympathy” (&agrave; la Smith) that we help the least well-off at the expense of the most well-off, encroaching on their individual rights? The issue is that society is also composed of the most well-off whose ideas of justice may not correspond to this highly pro-social stance. Indeed, everyone may not have the same theory of justice as that benevolent social planner who attempts to infuse “mutual sympathy” in all of us. 

Recognizing that people hold a mozaic of ideas of justice, the authors of the Report stress that one can find is at least one commonality among many theories of justice: the notion of self-respect and social respect (i.e. the respect we get from others in the society). This is very central to the Rawlsian conception of justice, but it is, in a sense, also tied to the Libertarian approach: the more the individual is enabled to use their resources freely, the more respect he is conferred by society, and the more self-respect he derives from such freedom. 

Now, given all this background on the political philosophy foundations of the Report, how do the authors define that golden standard? In general, a successful policy is one that leads to a more just society, but more specifically, it is “one that improves lives by providing a basis of **dignity for all** and **respect for each other and for society**.” (emphasis added) It is a policy that puts forth an inter-subjective idea of respect, one that recognizes that we don’t live in a vacuum, that individuals’ respect is intrinsically related to others, that we thrive when others do. Moreover, it is an idea that emphasizes respect as opposed to a more narrow/simplistic idea of material well-being. For example, one could live off social welfare fairly well, but be deprived of the social worth derived from having a productive role in the economy. 

One may naturally wonder whether the ideas of dignity and respect are overly abstract concepts worth enshrining in the Constitution, but not something that can guide concrete policy. However, it is worth appreciating that this is a necessary first step. All too frequently, policy-makers go into the weeds of designing policies that are not driven by any one explicit principle. It could simply be a policy desired by a certain constituency, or something determined by the narrow mandate of a department/ministry, or maybe an implicit principle of making everyone materially better off. Yet, as I mentioned above, all of these may not be too narrow for the task of a Basic Income that has the far-reaching effects for the whole society, today and tomorrow. 

### Making the analytical framework more concrete

The authors do appreciate that a theory of justice can be too elusive to constitute a guideline for good policy-making. For this reason, they take an additional step in making matters more concrete and argue that to best promote an individual’s self- and social respect is to ensure that their psychological needs are satisfied. Hence, the authors turn to an established psychological theory called self-determination theory.

Personally, I don’t find the leap from self-respect to self-determination to be very well founded, nor do the authors make a strong point for why they have chosen this particular psychological theory over another. However, taking this new framework for granted, I think it is a worthy attempt to put some clear structure on an otherwise elusive concept. 

The theory of self-determination purports that individuals need a sense of autonomy, a sense of efficacy and competence, and social connection. Hence, a successful Basic Income policy should aim to fulfill these three principles, and the authors break down the characteristics of such an ideal policy:

1.	Provides adequate resources to lift people out of poverty
2.	Creates simple and accessible programs to allocate resources
3.	Provides a sense of stability, reliability and security about fulfilling future needs
4.	Is responsive to different needs and circumstances 
5.	Provides opportunity to exercise autonomy 
6.	Creates a socially inclusive community
7.	Creates resilience to respond in times of crisis

Moreover, to make a policy weather the test of time, society needs to trust the social institutions implementing it and believe that their aim and implementation delivers on the promise to create a more just society. Hence, there are two more provisos for this desired policy:

8.	It is sustainable from a fiscal perspective and robust to the political cycle
9.	It requires buy-in from both beneficiaries and contributors to the program 

### Does the Basic Income policy meet the “Golden Standard”?

Before jumping to the answer, let us define the Basic Income using the fairly straightforward definition put forth in the Report: “Basic income means a policy that guarantees all members of a society a minimum amount income in a period.” The authors make an additional distinction in the context of BC: the policy would be applied to all adults (ages 18-64), since the senior and minor populations are already covered by federal basic income programs called Old Age Security and Canada Child Benefit.

When we contrast this policy against the requirements listed above, we see quite soon why it doesn’t check all the boxes. To begin with, a Universal Basic Income (UBI) which would award cash transfers independent of income would simply be too expensive for a fiscally sustainable program – contradicting item **#8**. Even a generous enough level of UBI may not be sufficient to cover for a lot of people’s basic needs (such as disability needs) – contradicting item **#1**. Hence, a targeted basic income would be better suited; however, this approach requires an extensive set of design parameters that introduce complexity and can add to the stigma that welfare recipients already experience – contradicting item **#6**. Moreover, a targeted program that is both fiscally sustainable, would likely introduce certain labor disincentives that are already common in social welfare systems, and which undermine buy-in from contributors to the system – contradicting item **#9**. 

Below, I am including a summary table shedding light on the adequacy of a Universal Basic Income (UBI), assuming a high and consistent level of cash transfers to cover for current and future basic needs. I encourage the reader to create thought experiments to see where the Basic Income may fail - or in what ideal situation the Basic Income policy would satisfy as many of the below. 


|             Analytic framework category            |                        Desired policy characteristic                        | Does UBI  meet this? |
|:------------------------------------:|:---------------------------------------------------------------------------:|:--------------------:|
|          Sense  of  Autonomy         | 1. Provides adequate resources to lift people out of poverty                |      Potentially     |
|                                      | 2. Creates simple and accessible programs to allocate resources             |         Yes          |
|                                      | 3. Provides a sense of stability and security about fulfilling future needs |          Yes          |
|                                      | 4. Provides opportunity to exercise autonomy                                |          Yes         |
| Sense  of  Efficacy  and  Competence | 5. Is responsive to different needs and circumstances                       |          No          |
|                                      | 6. Creates resilience to respond in times of crisis                         |          No          |
|          Social  Connection          | 7. Creates a socially inclusive community                                   |      Potentially     |
|             Public  trust            | 8. It is fiscally sustainable and robust to the political cycle             |          No          |
|                                      | 9. It requires buy-in from beneficiaries and contributors of the program    |          No          |

One thing is clear: no matter the design a Basic Income policy, it is bound to conflict with some or many of the analytic framework categories. Moreover, what we don't consider here is the opportunity cost of this policy! What are the things we may need to trade to get the benefits of a Basic Income! This is something the Report discusses in more detail in the context of British Columbia. 


## Conclusion
All in all, it does not seem that a Basic Income can easily pass a rigorous analytical framework. As soon as one delves into the nitty gritty of this policy, it loses its appeal as the magical silver bullet that many people tout as being able to save the welfare system. Rather than throwing the baby out with the bath water, the authors focus on how to improve the current social welfare system to aid people who fall through the cracks, and recommend implementing fixes that can push the system closer to a golden standard.

